services:

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-user}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-db}", "-U", "${POSTGRES_USER:-user}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  adminer:
    image: butopea/adminer
    ports:
      - "7080:8080"
    environment:
      ADMINER_DB: ${POSTGRES_DB:-db}
      ADMINER_PASSWORD: ${POSTGRES_PASSWORD:-password}
      ADMINER_SERVER: database
      ADMINER_USERNAME: ${POSTGRES_USER:-user}
      ADMINER_DRIVER: pgsql
      ADMINER_AUTOLOGIN: 1


volumes:
  database_data:
