name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:

  # ----------------------------
  #   BACKEND (Symfony / PHP)
  # ----------------------------
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend-symfony

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_pgsql
          tools: phpstan, cs2pr
          coverage: none

      - name: Create .env file 
        run: cp .env.example .env

      - name: Create .env.test file 
        run: cp .env.test.example .env.test

      - name: Install dependencies (Composer)
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Set JWT env vars
        run: |
          echo "JWT_SECRET_KEY=config/jwt/private.pem" >> $GITHUB_ENV
          echo "JWT_PUBLIC_KEY=config/jwt/public.pem" >> $GITHUB_ENV
          echo "JWT_PASSPHRASE=${{ secrets.JWT_PASSPHRASE }}" >> $GITHUB_ENV

      - name: Generate JWT keypair
        run: php bin/console lexik:jwt:generate-keypair --overwrite

      - name: Run tests (PHP-CS-Fixer, PHPStan, PHPUnit)
        run: composer test
        env:
          APP_DEBUG: 0

  # ----------------------------
  #   FRONTEND (Next.js)
  # ----------------------------
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-nextjs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
